# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - pip install poetry==1.1.11
    post_install:
      - pip install --upgrade 'setuptools<71.0.0'
      # TODO: Change to docs group after poetry upgrade
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install 


mkdocs:
  configuration: mkdocs.yml

