site_name: PD-DWI

repo_url: https://github.com/technionComputationalMRILab/PD-DWI/

theme:
  name: material
#  highlightjs: true
#  include_homepage_in_sidebar: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Training Configuration: training_configuration.md
  - Dataset Preprocessing: dataset_preprocessing.md

plugins:
  - plotly
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly


