dataset:
  labels:
    negative: Non-pCR
    positive: pCR
    require_test_labels: false

  time_points:
    - T0
    - T1
    - T2

  modalities:
    - ADC 0100
    - F

  mask: DWI MASK

training:
  features_transformer:
    radiomics:
      imageType:
        Original: {}
      setting:
        resampledPixelSpacing:  [1.27,1.27,4.0]
  feature_selection:
    k: 100
  classifier:
    verbosity: 1
    learning_rate: 0.01
    scale_pos_weight: balanced
    n_estimators: 1000
    max_depth: 20
    min_child_weight: 10
    subsample: 1
    eval_metric: auc