type: object
properties:
    dataset:
        type: object
        properties:
            labels:
                type: object
                properties:
                    negative:
                        type: string
                    positive:
                        type: string

            time_points:
                type: array
                items:
                    enum:
                        - T0
                        - T1
                        - T2
                minItems: 1
                uniqueItems: true
            modalities:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                    enum:
                        - ADC 0100
                        - F
                        - ADC 0100600800
                        - ADC 100600800
            mask:
                const: "DWI MASK"
    pipeline:
        type: object
        properties:
            features_transformer:
                type: object
                radiomics:
                    type: object
            feature_selection:
                $ref: '#/$defs/select_k_best'
            classifier:
                $ref: '#/$defs/xgboost_classifier'
    grid_search_cv:
        type: object
        properties:
            verbose:
                type: integer
                minimum: 1
            cv:
                type: integer
                minimum: 1
#            param_grid:
#                type: object
#                properties:
#                    classifier:
#                        $ref: '#/$defs/xgboost_classifier'
#                    feature_selection:
#                        $ref: '#/$defs/select_k_best'
        required:
            - scoring
            - cv
#            - param_grid

required:
    - dataset
    - pipeline

$defs:
    select_k_best:
        type: object
        properties:
            k:
                type: integer
                minimum: 1
    xgboost_classifier:
        type: object
        properties:
            verbosity:
                type: integer
                minimum: 1
            learning_rate:
                type: number
                minimum: 0
            scale_pos_weight:
                any_of:
                    - const: "balanced"
                    - type: number
                      minimum: 0
            n_estimators:
                type: integer
                minimum: 1
            max_depth:
                type: integer
                minimum: 1
            min_child_weight:
                type: number
                exclusive_minimum: 0
            subsample:
                type: number
                exclusive_minimum: 0
            eval_metric:
                const: "auc"